name: release please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: releasepleasestep
        uses: googleapis/release-please-action@v4
        with: 
          
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json


          token: ${{ secrets.HUB_TOKEN }} 


          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          
